import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import image from "../images/login_backgoround.png";
const SignInPage = () => {
    const [email, setEmail] = useState("hello@example.com");
    const [password, setPassword] = useState("Password");
    const [remember, setRemember] = useState(false);
    return (_jsx("div", { className: "container h-100", style: {
            backgroundSize: "cover",
        }, children: _jsx("div", { className: "row h-100 align-items-center justify-content-center", children: _jsx("div", { className: "col-xl-12", children: _jsx("div", { className: "card", children: _jsx("div", { className: "card-body p-0", children: _jsxs("div", { className: "row m-0", children: [_jsx("div", { className: "col-xl-6 col-md-6", children: _jsx("div", { children: _jsx("img", { src: image, className: "img-fix bitcoin-img sd-shape7", alt: "Bitcoin" }) }) }), _jsx("div", { className: "col-xl-6 col-md-6", children: _jsxs("div", { className: "sign-in-your py-4 px-2", children: [_jsx("h4", { className: "fs-20", children: "Sign in to your account" }), _jsx("span", { className: "fs-20", children: "Welcome! Login with your data that JUZENG provided you :)" }), _jsxs("form", { action: "index.html", children: [_jsxs("div", { className: "text-left", children: [_jsxs("div", { className: "mb-3", children: [_jsx("label", { className: "mb-1", children: _jsx("strong", { children: "Email" }) }), _jsx("input", { type: "email", className: "form-control", value: email, onChange: (e) => setEmail(e.target.value) })] }), _jsxs("div", { className: "mb-3", children: [_jsx("label", { className: "mb-1", children: _jsx("strong", { children: "Password" }) }), _jsx("input", { type: "password", className: "form-control", value: password, onChange: (e) => setPassword(e.target.value) })] })] }), _jsxs("div", { className: "row d-flex justify-content-between mt-4 mb-2", children: [_jsx("div", { className: "mb-3", children: _jsxs("div", { className: "form-check custom-checkbox ms-1", children: [_jsx("input", { type: "checkbox", className: "form-check-input", id: "basic_checkbox_1", checked: remember, onChange: () => setRemember(!remember) }), _jsx("label", { className: "form-check-label", htmlFor: "basic_checkbox_1", children: "Remember my preference" })] }) }), _jsx("div", { className: "mb-3", children: _jsx("a", { href: "page-forgot-password.html", children: "Forgot Password?" }) })] }), _jsx("div", { className: "text-center", children: _jsx("button", { type: "submit", className: "btn btn-primary btn-block", children: "Sign Me In" }) })] })] }) })] }) }) }) }) }) }));
};
export default SignInPage;
