# Generated by Django 5.1.2 on 2024-10-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='start date'),
        ),
    ]
