# Generated by Django 5.1.2 on 2024-11-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_lesson_group_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='flow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.flow'),
            preserve_default=False,
        ),
    ]
