# Generated by Django 5.1.2 on 2024-10-27 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_flow_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='end time date'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0, verbose_name='number of students'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='start time date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('elementary', 'Elementary'), ('pre-intermediate', 'Pre-intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-intermediate')], max_length=30, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='lesson link'),
        ),
    ]
