# Generated by Django 4.2.13 on 2024-11-10 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lesson_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MeetingParticipant',
        ),
    ]
